Add CloudFormation commands and enhance final-pipeline.yaml with EC2, CodeBuild, and CodeDeploy configurations

diff --git a/final-pipeline.yaml b/final-pipeline.yaml
--- a/final-pipeline.yaml
+++ b/final-pipeline.yaml
@@ -1,38 +1,250 @@
 AWSTemplateFormatVersion: '2010-09-09'
-Description: 'EC2 instance with IAM role and user data'
+Description: EC2 instance with IAM role and user data
 
 Parameters:
   SecurityGroup:
     Type: String
-    Description: 'Name of the security group for the EC2 instance'
-    Default: 'jenkins-agent'
+    Description: Name of the security group for the EC2 instance
+    Default: jenkins-agent
     MinLength: 1
-    
-  IamProfile:
-    Type: String
-    Description: 'ARN of the IAM Instance Profile for EC2 instance'
-    Default: 'ec2S3FullAccess'
-    MinLength: 1
-    
+
   KeyName:
     Type: AWS::EC2::KeyPair::KeyName
-    Description: 'Name of the SSH key pair to use for EC2 instance'
-    Default: 'keypair'
+    Description: Name of the SSH key pair to use for EC2 instance
+    Default: keypair
 Resources:
+
+  ##########################
+  # EC2 server configuration
+  ##########################
+  EC2S3FullAccessRole:
+    Type: AWS::IAM::Role
+    Properties:
+      AssumeRolePolicyDocument:
+        Version: '2012-10-17'
+        Statement:
+          - Effect: Allow
+            Principal:
+              Service: ec2.amazonaws.com
+            Action: sts:AssumeRole
+      ManagedPolicyArns:
+        - arn:aws:iam::aws:policy/AmazonS3FullAccess
+      RoleName: EC2S3FullAccessRole
+
+  EC2InstanceProfile:
+    Type: AWS::IAM::InstanceProfile
+    Properties:
+      Roles:
+        - !Ref EC2S3FullAccessRole
+      InstanceProfileName: EC2InstanceProfile
+
   EC2Instance:
     Type: AWS::EC2::Instance
     Properties:
       InstanceType: t2.micro
       ImageId: ami-0fd05997b4dff7aac
+      Tags:
+        - Key: Name
+          Value: jenkins-agent
       SecurityGroups:
         - !Ref SecurityGroup
-      IamInstanceProfile: !Ref IamProfile
+      IamInstanceProfile: !Ref EC2InstanceProfile
       KeyName: !Ref KeyName
-      UserData:
-        Fn::Base64: !Sub | 
+      UserData: !Base64
+        Fn::Sub: |
           #!/bin/bash
-          yum update -y
-          yum install httpd -y
-          systemctl start httpd
-          systemctl enable httpd
-          echo "<h1>Hello World from $(hostname -f)</h1>" > /var/www/html/index.html
+          # Update system packages
+          sudo yum update -y
+          # Install required dependencies
+          sudo yum install -y ruby wget
+          # Install AWS CodeDeploy agent
+          cd ~
+          wget https://aws-codedeploy-us-west-2.s3.us-west-2.amazonaws.com/latest/install
+          chmod +x ./install
+          sudo ./install auto
+          # Add MongoDB Repository
+          cat << 'EOF' | sudo tee /etc/yum.repos.d/mongodb-org-8.0.repo
+          [mongodb-org-8.0]
+          name=MongoDB Repository
+          baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/8.0/x86_64/
+          gpgcheck=1
+          enabled=1
+          gpgkey=https://pgp.mongodb.com/server-8.0.asc
+          EOF
+          # Install MongoDB components
+          sudo yum install -qy mongodb-mongosh-shared-openssl3
+          sudo yum install -y mongodb-org-8.0.4 mongodb-org-database-8.0.4 mongodb-org-server-8.0.4 mongodb-org-mongos-8.0.4 mongodb-org-tools-8.0.4
+          # Start MongoDB service
+          sudo systemctl start mongod
+          sudo systemctl enable mongod  # Enable MongoDB to start on boot
+          # Check services status
+          sudo service codedeploy-agent status
+          sudo systemctl status mongod
+          # Add error handling
+          if [ $? -ne 0 ]; then
+          echo "Error: Service check failed"
+          exit 1
+          fi
+
+  ##########################
+  # CodeBuild Configuration
+  ##########################
+
+  CodeBuildRole:
+    Type: AWS::IAM::Role
+    Properties:
+      AssumeRolePolicyDocument:
+        Version: '2012-10-17'
+        Statement:
+          - Effect: Allow
+            Principal:
+              Service: codebuild.amazonaws.com
+            Action: sts:AssumeRole
+      ManagedPolicyArns:
+        - arn:aws:iam::aws:policy/AmazonS3FullAccess
+        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
+      RoleName: CodeBuildRole
+
+  CodeBuildProject:
+    Type: AWS::CodeBuild::Project
+    Properties:
+      Name: !Sub ${AWS::StackName}-build
+      Artifacts:
+        Type: S3
+        Location: 123456-abdullah-bucket
+      Environment:
+        ComputeType: BUILD_GENERAL1_SMALL
+        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
+        Type: LINUX_CONTAINER
+      ServiceRole: !Ref CodeBuildRole
+      Source:
+        Type: GITHUB
+        Auth:
+          Type: OAUTH
+        Location: https://github.com/realAbdullah4504/aws-codedeploy.git
+        BuildSpec: buildspec.yaml
+      SourceVersion: cloud-formation-stack
+
+  ##########################
+  # CodeDeploy Configuration
+  ##########################
+
+  CodeDeployRole:
+    Type: AWS::IAM::Role
+    Properties:
+      AssumeRolePolicyDocument:
+        Version: '2012-10-17'
+        Statement:
+          - Effect: Allow
+            Principal:
+              Service: codedeploy.amazonaws.com
+            Action: sts:AssumeRole
+      ManagedPolicyArns:
+        - arn:aws:iam::aws:policy/AmazonS3FullAccess
+        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
+
+      RoleName: CodeDeployRole
+
+  CodeDeployApplication:
+    Type: AWS::CodeDeploy::Application
+    Properties:
+      ApplicationName: !Sub ${AWS::StackName}-app
+      ComputePlatform: Server
+
+  CodeDeployDeploymentGroup:
+    Type: AWS::CodeDeploy::DeploymentGroup
+    DependsOn: 
+      - CodeDeployApplication
+      - EC2Instance
+    Properties:
+      ApplicationName: !Ref CodeDeployApplication
+      DeploymentGroupName: !Sub "${AWS::StackName}-deployment-group"
+      ServiceRoleArn: !GetAtt CodeDeployRole.Arn
+      DeploymentStyle:
+        DeploymentType: IN_PLACE
+        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
+      DeploymentConfigName: CodeDeployDefault.AllAtOnce
+      Ec2TagFilters:
+        - Key: Name
+          Value: jenkins-agent
+          Type: KEY_AND_VALUE
+      AutoRollbackConfiguration:
+        Enabled: true
+        Events:
+          - DEPLOYMENT_FAILURE
+
+  ##########################
+  # CodePipeline resources
+  ##########################
+  CodePipelineArtifactStoreS3Bucket:
+    Type: AWS::S3::Bucket
+    Properties:
+      VersioningConfiguration:
+        Status: Enabled
+  
+  CodePipelineRole:
+    Type: AWS::IAM::Role
+    Properties:
+      AssumeRolePolicyDocument:
+        Version: '2012-10-17'
+        Statement:
+          - Effect: Allow
+            Principal:
+              Service: codepipeline.amazonaws.com
+            Action: sts:AssumeRole
+      ManagedPolicyArns:
+        - arn:aws:iam::588738579221:policy/service-role/AWSCodePipelineServiceRole-ap-south-1-final
+      RoleName: CodePipelineRole
+  
+  CodePipeline:
+    Type: AWS::CodePipeline::Pipeline
+    Properties:
+      RoleArn: !GetAtt CodePipelineRole.Arn
+      ArtifactStore:
+        Type: S3
+        Location: !Ref CodePipelineArtifactStoreS3Bucket
+      Stages:
+        - Name: Source
+          Actions:
+            - Name: Source
+              ActionTypeId:
+                Category: Source
+                Owner: AWS
+                Version: "1"
+                Provider: CodeStarSourceConnection
+              OutputArtifacts:
+                - Name: SourceOutput
+              Configuration:
+                FullRepositoryId: realAbdullah4504/aws-codedeploy
+                BranchName: cloud-formation-stack
+                ConnectionArn: arn:aws:codeconnections:ap-south-1:588738579221:connection/51340ca1-e197-4f09-ab0c-bccdc806b303
+              RunOrder: 1
+        - Name: Build
+          Actions:
+            - Name: Build
+              ActionTypeId:
+                Category: Build
+                Owner: AWS
+                Version: "1"
+                Provider: CodeBuild
+              InputArtifacts:
+                - Name: SourceOutput
+              OutputArtifacts:
+                - Name: BuildOutput
+              Configuration:
+                ProjectName: !Ref CodeBuildProject
+              RunOrder: 1
+        - Name: Deploy
+          Actions:
+            - Name: Deploy
+              ActionTypeId:
+                Category: Deploy
+                Owner: AWS
+                Version: "1"
+                Provider: CodeDeploy
+              InputArtifacts:
+                - Name: BuildOutput
+              Configuration:
+                ApplicationName: !Ref CodeDeployApplication
+                DeploymentGroupName: !Ref CodeDeployDeploymentGroup
+              RunOrder: 1
